#!/bin/bash
sudo apt-get install build-essential libgl1-mesa-dev libx11-dev libxext-dev libxrandr-dev libglu1-mesa-dev freeglut3-dev make gcc ripgrep unzip git xclip curl xinput brightnessctl shutter acpi lxqt-powermanagement -y

: ' nvim
curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
sudo rm -rf /opt/nvim-linux64
sudo mkdir -p /opt/nvim-linux64
sudo chmod a+rX /opt/nvim-linux64
sudo tar -C /opt -xzf nvim-linux64.tar.gz
'

# make it available in /usr/local/bin, distro installs to /usr/bin
# sudo ln -sf /opt/nvim-linux64/bin/nvim /usr/local/bin/

: '
cat bash >> $HOME/.bashrc
cp -r nvim/ $HOME/.config/
cp -r awesome/ $HOME/.config/
cp -r jcc /usr/local/bin/ 
cd coomer && g++ coomer.cpp -lgl -lglu -lx11 -lxrandr -lxext -o coomer && sudo cp -r coomer /usr/local/bin/
'
